include:
  - infra.yaml

services:
  backend:
    build: ./Server
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORTS=80
      - HTTPS_PORTS=
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=Research;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379,connectTimeout=500,syncTimeout=500,responseTimeout=500,abortConnect=false
  frontend:
    build: ./Client
    ports:
      - "3000:80"
    

