services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_strong_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
#     volumes:
#       - sql_data:/var/opt/mssql

# volumes:
#   sql_data:
#     name: sql_data